CREATE TABLE IF NOT EXISTS newsletter_sender_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_kind text NOT NULL CHECK (match_kind IN ('domain', 'address')),
  pattern text NOT NULL,
  source_name text NOT NULL,
  CONSTRAINT newsletter_sender_rules_match_unique UNIQUE (match_kind, pattern)
);

CREATE TABLE IF NOT EXISTS rss_feeds (
  source_name text PRIMARY KEY,
  url text NOT NULL,
  last_error text,
  last_error_at timestamptz,
  last_success_at timestamptz
);

INSERT INTO newsletter_sender_rules (match_kind, pattern, source_name) VALUES
  ('domain', 'astralcodexten.com', 'Astral Codex Ten'),
  ('domain', 'substack.com', ''),
  ('domain', 'erikhoel.substack.com', 'The Intrinsic Perspective'),
  ('domain', 'exponentialview.co', 'Exponential View'),
  ('domain', 'importai.substack.com', 'Import AI'),
  ('domain', 'thediff.co', 'The Diff'),
  ('domain', 'notboring.co', 'Not Boring'),
  ('domain', 'bloomberg.net', 'Money Stuff'),
  ('domain', 'sinocism.com', 'Sinocism'),
  ('domain', 'generalist.com', 'The Generalist'),
  ('domain', 'fs.blog', 'Farnam Street Brain Food'),
  ('domain', 'worksinprogress.news', 'Works in Progress'),
  ('domain', 'experimental-history.com', 'Experimental History'),
  ('domain', 'noahpinion.substack.com', 'Noahpinion'),
  ('domain', 'foreignpolicy.com', 'China Brief'),
  ('domain', 'tldr.tech', 'TLDR AI'),
  ('domain', 'technologyreview.com', 'MIT Technology Review'),
  ('domain', 'ben-evans.com', 'Benedict Evans'),
  ('domain', 'semianalysis.com', 'SemiAnalysis'),
  ('domain', 'fortune.com', 'Term Sheet'),
  ('domain', 'chinatalk.media', 'ChinaTalk'),
  ('domain', 'hackernewsletter.com', 'Hacker Newsletter'),
  ('domain', 'quantamagazine.org', 'Quanta Magazine'),
  ('domain', 'foundmyfitness.com', 'FoundMyFitness'),
  ('domain', 'insightforward.co.uk', 'PESTLE and MORTAR'),
  ('domain', 'whatsonweibo.com', 'What''s on Weibo'),
  ('domain', 'interconnect.substack.com', 'Interconnected'),
  ('domain', 'warontherocks.com', 'War on the Rocks'),
  ('domain', 'palladiummag.com', 'Palladium Magazine'),
  ('domain', 'followingtheyuan.substack.com', 'Following the Yuan'),
  ('domain', 'chineseconsumers.news', 'Following the Yuan'),
  ('domain', 'console.dev', 'Console.dev'),
  ('domain', 'bytes.dev', 'Bytes.dev'),
  ('domain', 'neuronewsinternational.com', 'NeuroNews International'),
  ('domain', 'netzpolitik.org', 'Netzpolitik.org'),
  ('address', 'astralcodexten@substack.com', 'Astral Codex Ten'),
  ('address', 'bill@sinocism.com', 'Sinocism'),
  ('address', 'letters@noahpinion.substack.com', 'Noahpinion'),
  ('address', 'jack@importai.substack.com', 'Import AI'),
  ('address', 'packy@notboring.co', 'Not Boring')
ON CONFLICT (match_kind, pattern) DO NOTHING;

INSERT INTO rss_feeds (source_name, url) VALUES
  ('Astral Codex Ten', 'https://astralcodexten.substack.com/feed'),
  ('The Intrinsic Perspective', 'https://erikhoel.substack.com/feed'),
  ('Exponential View', 'https://www.exponentialview.co/feed'),
  ('Import AI', 'https://importai.substack.com/feed'),
  ('Not Boring', 'https://notboring.substack.com/feed'),
  ('Money Stuff', 'https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss'),
  ('Sinocism', 'https://sinocism.substack.com/feed'),
  ('The Generalist', 'https://generalist.substack.com/feed'),
  ('Farnam Street Brain Food', 'https://fs.blog/feed'),
  ('Works in Progress', 'https://www.worksinprogress.news/feed'),
  ('Experimental History', 'https://experimental-history.substack.com/feed'),
  ('Noahpinion', 'https://noahpinion.substack.com/feed'),
  ('MIT Technology Review', 'https://www.technologyreview.com/feed'),
  ('SemiAnalysis', 'https://semianalysis.substack.com/feed'),
  ('ChinaTalk', 'https://chinatalk.substack.com/feed'),
  ('Quanta Magazine', 'https://www.quantamagazine.org/feed'),
  ('What''s on Weibo', 'https://www.whatsonweibo.com/feed'),
  ('Interconnected', 'https://interconnect.substack.com/feed'),
  ('War on the Rocks', 'https://warontherocks.com/feed'),
  ('Palladium Magazine', 'https://www.palladiummag.com/feed'),
  ('Following the Yuan', 'https://www.chineseconsumers.news/feed'),
  ('Console.dev', 'https://console.dev/rss.xml'),
  ('NeuroNews International', 'https://neuronewsinternational.com/feed')
ON CONFLICT (source_name) DO NOTHING;
